name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: 🔧 Setup Java with cache
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 21
          cache: "gradle"

      - name: ✅ Grant gradlew permissions
        run: chmod +x ./gradlew

      - name: 🛠️ Build with Gradle
        run: ./gradlew build shadowJar

      - name: 📦 Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          draft: false
          files: build/libs/email2username-mapper-1.0-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
